# =====================================================
# Docker Compose - R iRepair Frontend Only
# =====================================================

version: '3.8'

services:
  # ===== Base de Données PostgreSQL =====
  postgres:
    image: postgres:15-alpine
    container_name: rirepair-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: rirepair
      POSTGRES_USER: rirepair_user
      POSTGRES_PASSWORD: rirepair_secure_password_change_this
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./database/seeds.sql:/docker-entrypoint-initdb.d/02-seeds.sql
    ports:
      - "5432:5432"
    networks:
      - rirepair-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rirepair_user -d rirepair"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ===== Frontend Next.js (avec APIs intégrées) =====
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: rirepair-frontend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 3000
      
      # Base de données (connexion directe depuis le frontend)
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: rirepair_user
      DB_PASSWORD: rirepair_secure_password_change_this
      DB_NAME: rirepair
      
      # Application
      NEXT_PUBLIC_BASE_URL: http://localhost:3000
      NEXT_PUBLIC_APP_NAME: R iRepair
      NEXT_PUBLIC_APP_VERSION: "1.0.0"
      
    ports:
      - "3000:3000"
    networks:
      - rirepair-network
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3

# =====================================================
# Volumes Persistants
# =====================================================
volumes:
  postgres_data:
    driver: local

# =====================================================
# Réseau
# =====================================================
networks:
  rirepair-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
